// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZM7my8GjjuBTrH3XRNgWJAcFmCKzb1sQ',
    appId: '1:721598927062:web:0b1021415aee6b09c3f977',
    messagingSenderId: '721598927062',
    projectId: 'app-freelance-f3dee',
    authDomain: 'app-freelance-f3dee.firebaseapp.com',
    databaseURL:
        'https://app-freelance-f3dee-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-freelance-f3dee.firebasestorage.app',
    measurementId: 'G-3GFQWVZ0XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACMKoyxUw13HZKOvdkTpQ1td_o-4ywczk',
    appId: '1:721598927062:android:a4588de1897151f9c3f977',
    messagingSenderId: '721598927062',
    projectId: 'app-freelance-f3dee',
    databaseURL:
        'https://app-freelance-f3dee-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-freelance-f3dee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUEOyN24y-4z8L0-yzJxePXGGTMwRJD0A',
    appId: '1:721598927062:ios:c834dccb6c153713c3f977',
    messagingSenderId: '721598927062',
    projectId: 'app-freelance-f3dee',
    databaseURL:
        'https://app-freelance-f3dee-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-freelance-f3dee.firebasestorage.app',
    iosBundleId: 'com.general.worker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUEOyN24y-4z8L0-yzJxePXGGTMwRJD0A',
    appId: '1:721598927062:ios:c834dccb6c153713c3f977',
    messagingSenderId: '721598927062',
    projectId: 'app-freelance-f3dee',
    databaseURL:
        'https://app-freelance-f3dee-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-freelance-f3dee.firebasestorage.app',
    iosBundleId: 'com.general.worker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZM7my8GjjuBTrH3XRNgWJAcFmCKzb1sQ',
    appId: '1:721598927062:web:b0c240fd039963c2c3f977',
    messagingSenderId: '721598927062',
    projectId: 'app-freelance-f3dee',
    authDomain: 'app-freelance-f3dee.firebaseapp.com',
    databaseURL:
        'https://app-freelance-f3dee-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-freelance-f3dee.firebasestorage.app',
    measurementId: 'G-TY6Q9XZPNV',
  );
}
